# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 678bae0820c1454ef8379cd79b34288f54c660eca9c9f29fd63fed7062a4fa90144ee907aa95b2468ff97037d452944e412d0dc30c367464879f2055303cfda8

test:
  secret_key_base: 74fbc6ec533eea6e52886532b7941485b8b2fb264e883c482b995c4c25f5582f9db26f31fd4b25c34c4e535790d37de60dd690c3b6b2f3ce6c03ff26d489089a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
